# Generated by Django 3.2 on 2025-03-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactmemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=150)),
                ('email_model', models.EmailField(max_length=254)),
                ('contactnumber_model', models.CharField(max_length=12)),
                ('designation_model', models.CharField(max_length=100)),
                ('subject_model', models.CharField(max_length=150)),
                ('message_model', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='projectsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('projectimg', models.ImageField(upload_to='projectsimg/')),
                ('projectdesc', models.CharField(max_length=500)),
                ('projectcategory', models.CharField(max_length=50)),
                ('projectdate', models.CharField(max_length=11)),
                ('projecturl', models.CharField(default='1234', max_length=1000000)),
                ('projectgithuburl', models.CharField(default='1234', max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='reviewmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewdesc', models.CharField(max_length=300)),
                ('reviewimg', models.FileField(upload_to='reviewimg/')),
                ('reviewname', models.CharField(max_length=20)),
                ('reviewprofession', models.CharField(max_length=50)),
            ],
        ),
    ]
